---
title: "PCA_analysis"
authors: Selina Dreesman
date: "2024-04-03"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, include=FALSE}
library(dplyr)
library(ggplot2)
library(pheatmap)
library(tidyr)
library(RColorBrewer)
library(ggrepel)
library(Seurat)
library(Matrix)
library(here)

```

```{r load data, include=FALSE}
features <- read.csv(here("raw_data/data/e85_feature_metadata.csv.gz"))
samples <- read.csv(here("raw_data/data/e85_sample_metadata.csv"))



# load the mtx file
counts <- ReadMtx(here("raw_data/data/e85_count_matrix.mtx.gz"), 
                  here("raw_data/data/e85_sample_metadata.csv"),
                  here("raw_data/data/e85_feature_metadata.csv.gz"),
                  feature.sep = ",",
                  cell.sep = ",",
                  cell.column = 3,
                  feature.column = 1,
                  skip.cell = 1,
                  skip.feature = 1)

```

```{r seurat, include=FALSE}
# create a seurat object
seurat <- CreateSeuratObject(counts = counts, 
                             project = "mouse-embryo", 
                             min.cells = 3, 
                             min.features = 2500)
seurat



```

```{r data quality clusters specific, echo=FALSE, fig.width=15, fig.height=5}
# number of features, number of counts, percentage MT 

# Subset the Seurat object to include only cells from cluster E8.5-#
cluster_subset <- subset(seurat, idents = c("E8.5-17", "E8.5-2"))
cluster_subset[["percent.mt"]] <- PercentageFeatureSet(cluster_subset, pattern = "^mt-")

# Create a violin plot for the subset
VlnPlot(cluster_subset, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

#view identities
table(Idents(seurat))
```

```{r data quality, echo=FALSE, fig.width=15, fig.height=5}
# Calculate percentage of mitochondrial genes for the subset
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^mt-")

# Create a violin plot for the subset
VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

#view identities
table(Idents(seurat))
```

```{r feature scatterplots, echo=FALSE}
# feature scatter
cnt_ftr <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
cnt_mt <- FeatureScatter(seurat, feature1 = "nCount_RNA", feature2 = "percent.mt")

cnt_ftr
cnt_mt

```

```{r subset data, echo=FALSE,  fig.width=15, fig.height=5}
# subset the data
seurat <- subset(seurat, subset = nFeature_RNA > 7500 & nFeature_RNA < 12500 & percent.mt < 5)

# normalize
seurat <- NormalizeData(seurat, normalization.method = "LogNormalize", scale.factor = 10000)

# Create a violin plot for normalization check
VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

```

```{r identy top10 genes, echo=FALSE, fig.width=15, fig.height=5}
# Find variable features 
seurat <- FindVariableFeatures(seurat, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(seurat), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(seurat) + 
  theme(legend.position="top")
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE) + 
  theme(legend.position="top")

plot1
plot2
```

```{r scaling, echo=FALSE}

all.genes <- rownames(seurat)

seurat <- ScaleData(seurat, features = all.genes)

# result stored in seurat[["RNA"]]$scale.data

```

```{r PCA, echo=FALSE, fig.width=15, fig.height=5}

seurat <- RunPCA(seurat, features = VariableFeatures(object = seurat))

print(seurat[["pca"]], dims = 1:5, nfeatures = 5)

ElbowPlot(seurat)
VizDimLoadings(seurat, dim=1:2, reduction = "pca")
DimPlot(seurat, reduction = "pca") # add + NoLegend() incase you don't want to involve a legend to your plot

```

```{r save object, echo=FALSE}

saveRDS(seurat, file = "~/projecticum/splicing/raw_data/data/umap_seurat_embryoE85.rds")

```




```{r cluster markers, echo=FALSE, fig.width=15, fig.height=20}
# run from here if you have the seurat object already
seurat <- readRDS("~/projecticum/splicing/raw_data/data/umap_seurat_embryoE85.rds")

# find markers for every cluster compared to all remaining cells, 
# report only the positive ones
markers <- FindAllMarkers(seurat, only.pos = TRUE)

markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10


DoHeatmap(seurat, features = top10$gene)

```



```{r, echo=false}
RunUMAP(seurat, dims = 1:30, verbose = FALSE)

seurat <- FindNeighbors(seurat, dims = 1:30)
seurat <- FindClusters(seurat)


DimPlot(seurat, label = TRUE)
```


```{r, echo=FALSE}


```